# Generated by Django 4.2.2 on 2023-11-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.TextField()),
                ('sbranch', models.TextField()),
                ('saddress', models.TextField()),
                ('srollnumber', models.TextField()),
                ('sphonenumber', models.TextField()),
            ],
        ),
    ]
