# Generated by Django 4.2.7 on 2023-11-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='saddress',
            new_name='passw',
        ),
        migrations.RenameField(
            model_name='studentdata',
            old_name='sbranch',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='sname',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='sphonenumber',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='srollnumber',
        ),
    ]
