# Generated by Django 4.2.7 on 2023-11-23 08:45

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_rename_saddress_studentdata_passw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='passw',
            field=models.TextField(verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='user',
            field=models.TextField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
