# Generated by Django 4.2.7 on 2023-11-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_alter_studentdata_passw_alter_studentdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='passw',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='user',
            field=models.TextField(),
        ),
    ]
