# Generated by Django 4.2.7 on 2023-11-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_alter_studentdata_passw_alter_studentdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='passw',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='user',
            field=models.CharField(max_length=70),
        ),
    ]
