# Generated by Django 4.2.7 on 2023-11-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_yourmodel_alter_employees_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
        migrations.AddField(
            model_name='employees',
            name='rollno',
            field=models.CharField(default='your_default_value', max_length=100),
        ),
    ]
