# Generated by Django 4.2.7 on 2023-11-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_alter_employees_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employees',
            name='rollno',
            field=models.TextField(max_length=10),
        ),
    ]
